name: Release
on:
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install frontend dependencies
        run: pnpm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^2.0.0-beta"

      # 为macOS添加额外的目标架构
      - name: Add macOS target architectures
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      # 为不同平台配置不同的构建参数
      - name: Build the app (macOS)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_BUNDLER_DMG_IGNORE_CI: true
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Jedi v${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          args: --target universal-apple-darwin --verbose
          tauriScript: pnpm tauri

      # 为Windows和Linux构建
      - name: Build the app (Windows & Linux)
        if: matrix.platform != 'macos-latest'
        uses: tauri-apps/tauri-action@v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 对于 Ubuntu 平台的额外环境变量
          TAURI_LINUX_WEBKIT2GTK: true
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Jedi v${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          tauriScript: pnpm tauri
          args: --verbose